name: Release

on:
  push

jobs:
  release-linux:
    runs-on: ubuntu-20.04


    steps:
      - uses: actions/checkout@v4
 
          

  release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
            


  release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4



  dispatch:
    runs-on: ubuntu-20.04
    needs: [release-macos,release-linux,release-windows]
    steps:
      - uses: actions/checkout@v4
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: my-event
          client-payload: '{"ION_KIT_VERSION": "33.0.0"}'
    
  
          

