name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      

  release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

 
  release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4



