name: Release

on:
  push

jobs:
  release-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        shell: bash
        run: |
          # Halide
          curl --fail https://github.com/halide/Halide/releases/download/v17.0.1/Halide-1
  

      

  release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        shell: bash
        run: |
          # Halide
          curl --fail https://github.com/halide/Halide/releases/download/v17.0.1/Halide-1
  


 
  release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4



