name: Release

on:
  push

jobs:
  release-linux:
    runs-on: ubuntu-20.04


    steps:
      - uses: actions/checkout@v4
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: xinyuli1204/ion-kit
          event-type: my-event
          client-payload: '{"ION_KIT_VERSION": "1.0.0"}'
          

  release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
            
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: xinyuli1204/ion-kit
          event-type: my-event
          client-payload: '{"ION_KIT_VERSION": "1.0.0"}'
          

  release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: xinyuli1204/ion-kit
          event-type: my-event
          client-payload: '{"ION_KIT_VERSION": "1.0.0"}'
          

