name: VCPKG check 

on: 
  push:
    branches:
      - main

jobs:
  check-vcpkg:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest CMake
        uses: lukka/get-cmake@latest


      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1



      - name: Check PowerShell version
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git && ./vcpkg/bootstrap-vcpkg.bat
          ${{ github.workspace }}/vcpkg/vcpkg.exe install --triplet=x64-windows-static


  build-and-test:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Setup dependencies
        shell: bash
        run: |
          # zlib, libjpeg, libpng
          git clone https://github.com/microsoft/vcpkg.git && bash vcpkg/bootstrap-vcpkg.sh
          ${{ github.workspace }}/vcpkg/vcpkg install 


  build-and-test-macos:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      runs-on: macos-latest
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Get latest CMake
          uses: lukka/get-cmake@latest
  
        - name: Setup dependencies
          shell: bash
          run: |
            # zlib, libjpeg, libpng
            git clone https://github.com/microsoft/vcpkg.git && bash vcpkg/bootstrap-vcpkg.sh
            ${{ github.workspace }}/vcpkg/vcpkg install 



          
