name: VCPKG check 

on: 
  push:
    branches:
      - main

jobs:
  check-vcpkg:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PowerShell version
        run: |
          vcpkg install
          # git clone https://github.com/microsoft/vcpkg.git
          # cd vcpkg
          # git checkout 2024.09.30
          # sudo bash bootstrap-vcpkg.sh  && cd ../
          # ${{ github.workspace }}/vcpkg/vcpkg install
          
          
          
