name: VCPKG check 

on: 
  push:
    branches:
      - main

jobs:
  check-vcpkg:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PowerShell version
        run: |
          vcpkg install --triplet=x64-windows-static
          # git clone https://github.com/microsoft/vcpkg.git
          # cd vcpkg
          # git checkout 2024.09.30
          # .\bootstrap-vcpkg.bat  && cd ../
          # ${{ github.workspace }}\vcpkg\vcpkg.exe install
          
          
          
